# Generated by Django 4.0.1 on 2022-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='age',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
